services:
  backend:
    image: node:18-alpine
    container_name: poss-backend-container
    command: sh -c 'npm install && npm run start:dev'
    working_dir: /home/poss-backend
    ports:
      - 3000:3000
    volumes:
      - ./backend:/home/poss-backend
    environment:
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: AjboyIan_321
      DATABASE_NAME: poss
      APP_ENV: dev
  frontend:
    image: node:18-alpine
    container_name: poss-frontend-container
    command: sh -c 'npm install && npm run dev'
    working_dir: /home/poss-frontend
    ports:
      - 5173:5173
      - 6006:6006
    volumes:
      - ./frontend:/home/poss-frontend
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - poss-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: AjboyIan_321
      MYSQL_DATABASE: poss

volumes:
  poss-mysql-data: