services:
  backend:
    build: ./backend
    container_name: poss-backend-container
    ports:
      - 3000:3000
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: AjboyIan_321
      DATABASE_NAME: poss
      APP_ENV: dev
  frontend:
    build: ./frontend
    container_name: poss-frontend-container
    command: 'npm run dev'
    ports:
      - 5173:5173
      - 6006:6006
    volumes:
      - ./frontend/index.html:/home/poss-frontend/index.html
      - ./frontend/public:/home/poss-frontend/public
      - ./frontend/vite.config.ts:/home/poss-frontend/vite.config.ts
      - ./frontend/tsconfig.json:/home/poss-frontend/tsconfig.json
      - ./frontend/tsconfig.node.json:/home/poss-frontend/tsconfig.node.json
      - ./frontend/src:/home/poss-frontend/src
      - ./frontend/.storybook:/home/poss-frontend/.storybook
      - ./frontend/cli:/home/poss-frontend/cli
      - ./frontend/package.json:/home/poss-frontend/package.json
      - ./frontend/package-lock.json:/home/poss-frontend/package-lock.json
  mysql:
    image: mysql:8.0
    volumes:
      - poss-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: AjboyIan_321
      MYSQL_DATABASE: poss

volumes:
  poss-mysql-data: